### ISSUE TITLE
Create a method to get the transcription from Python

### ISSUE THREAD

**Issue by TheOriginalAn3** [TheOriginalAn3/vokabel_trainer#20]
```
    // TODO Create a method to get the transcription from Python
```

https://github.com/TheOriginalAn3/vokabel_trainer/blob/6129d073bb11816d77e38a30fd4c38f3e215605a/src/SpeechRecognition.java#L51

**Comment by Selin-SenSei** [comment]
NERVENZUSAMMENBRUCH
