### ISSUE TITLE
Show a random vocab in "jTextPane_ToTranslate" based on translation language after jTextField1ActionPerformed() @Selin-SenSei

### ISSUE THREAD

**Issue by TheOriginalAn3** [TheOriginalAn3/vokabel_trainer#25]
```
    // TODO Show a random vocab in "jTextPane_ToTranslate" based on translation language after jTextField1ActionPerformed() @Selin-SenSei
```

https://github.com/TheOriginalAn3/vokabel_trainer/blob/0af26c64be4fe26db654d901ffb9e0a0fdbdbb2e/src/ui/MyGUI.java#L489

Nachdem der Benutzer ein wort eingegeben hat oder Spracherkennung ein wort erkannt hat soll ein neues Vokabel abgefragt werden

**Comment by Selin-SenSei** [comment]
23.06; Zeile 509-510
